name: Run NYT Spelling Bee Scraper

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py > answers.json
          echo "Scraper completed. Output:"
          cat answers.json

      - name: Compute date label
        id: meta
        run: echo "today=$(date -u +%F)" >> "$GITHUB_OUTPUT"

      - name: Commit and push results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Spelling Bee answers for ${{ steps.meta.outputs.today }}"
          file_pattern: answers.json
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          skip_dirty_check: false
          skip_fetch: false